version: "3"
services:
  node:
    build:
     context: .
     dockerfile: docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run dev"
    environment:
      HOST: 0.0.0.0
      ES_HOST: "https://bigdata4tourism.davinci.bz.it/elasticsearch/"
    ports:
      - "3000:3000"
