name: CI/CD

on:
  push:
  pull_request:

env:
  AWS_REGION : "eu-west-1"
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: noi-techpark/github-actions/npm-test@v2
        with:
          lint-enabled: false
          node-version: ${{env.NODE_VERSION}}

  deploy-test:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "test-bigdata4tourism-web"
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_ES_HOST: "https://bigdata4tourism.davinci.bz.it/elasticsearch/"

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run generate
          node-version: ${{env.NODE_VERSION}}

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  deploy-prod:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/prod'
    needs: test
    concurrency: deploy-prod
    env:
      AWS_S3_BUCKET_NAME : "prod-bigdata4tourism-web"
      SCRIPTS_HOST: 'https://scripts.opendatahub.com'
    steps:
      - uses: actions/checkout@v2

      - name: Change scripts host to prod
        run: sed -i -e "s%https://scripts.opendatahub.testingmachine.eu%${{env.SCRIPTS_HOST}}%g" nuxt.config.js

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_ES_HOST: "https://kibanapublic.bigdata4tourism.davinci.bz.it/elasticsearch/"


      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run generate
          node-version: ${{env.NODE_VERSION}}

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist
